services:
    - type: web
      name: legal-rag-engine
      env: python
      buildCommand: pip install -r requirements.txt
      startCommand: chmod +x start.sh && ./start.sh
      envVars:
          - key: GEMINI_API_KEY
            sync: false
          - key: EMBEDDING_MODEL
            value: sentence-transformers/all-MiniLM-L6-v2
          - key: LLM_MODELS
            value: gemini-2.0-flash-lite,gemma-3-27b-it
